name: Naukri Refresh

on:
  schedule:
    # Runs every day at 3:30 AM UTC = 9:00 AM IST
    - cron: '30 3 * * *'
  workflow_dispatch:  # allows manual trigger from GitHub Actions tab

jobs:
  refresh_naukri:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Naukri Automation
        env:
          NAUKRI_USERNAME: ${{ secrets.NAUKRI_USERNAME }}
          NAUKRI_PASSWORD: ${{ secrets.NAUKRI_PASSWORD }}
        run: |
          python naukri_client.py --refresh
